/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ppaproj;


import java.awt.print.PrinterException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Hp
 */
public class Details extends javax.swing.JFrame {

    /**
     * Creates new form Details
     */
    public Details() {
        initComponents();
        Connect();
        load();
    }

    Connection con;
    PreparedStatement pst;
    DefaultTableModel df;

    public void Connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/autocarservice", "root", "");

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Details.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void load() {
        int a;
        try {
            pst = con.prepareStatement("select * from spareparts");
            ResultSet rs = pst.executeQuery();

            ResultSetMetaData rd = rs.getMetaData();
            a = rd.getColumnCount();
            df = (DefaultTableModel) jTable3.getModel();
            df.setRowCount(0);

            while (rs.next()) {
                Vector v2 = new Vector();
                for (int i = 1; i <= a; i++) {
                    v2.add(rs.getInt("id"));
                    v2.add(rs.getString("Spare_Part"));
                    v2.add(rs.getString("Description"));
                    v2.add(rs.getString("Barcode"));
                    v2.add(rs.getString("Qty"));
                    v2.add(rs.getString("Cost_Price"));
                    v2.add(rs.getString("Rental_Price"));
                    v2.add(rs.getString("Reorder_Level"));

                }
                df.addRow(v2);

            }

        } catch (SQLException ex) {
            Logger.getLogger(Details.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtsparepart = new javax.swing.JTextField();
        txtbarcode = new javax.swing.JTextField();
        txtcost_price = new javax.swing.JTextField();
        txtreorder_level = new javax.swing.JTextField();
        txtdescription = new javax.swing.JTextField();
        txtrental_price = new javax.swing.JTextField();
        txtqty = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 550));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Spare Parts");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setText("Spare Part");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 128, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("Description");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 128, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setText("Barcode");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 178, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setText("Qty");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 178, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setText("Cost Price");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 225, -1, 14));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setText("Sales Price");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 224, -1, -1));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setText("Reorder Level");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 262, -1, -1));

        txtsparepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsparepartActionPerformed(evt);
            }
        });
        jPanel1.add(txtsparepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 126, 174, -1));
        jPanel1.add(txtbarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 176, 174, -1));
        jPanel1.add(txtcost_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 222, 174, -1));
        jPanel1.add(txtreorder_level, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 260, 174, -1));
        jPanel1.add(txtdescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 126, 174, -1));
        jPanel1.add(txtrental_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 222, 174, -1));
        jPanel1.add(txtqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 176, 174, -1));

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 320, -1, -1));

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 320, -1, -1));

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 320, -1, -1));

        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 320, -1, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Part ID", "Spare Part", "Description", "Barcode", "Qty", "Cost Price", "Rental Price", "Reorder Level"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 374, 641, 177));

        jButton5.setText("Close");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 320, -1, -1));

        jButton6.setText("Print");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        df = (DefaultTableModel) jTable3.getModel();
        int selected = jTable3.getSelectedRow();

        int id = Integer.parseInt(df.getValueAt(selected, 0).toString());

        String sparepart = txtsparepart.getText();
        String description = txtdescription.getText();
        String barcode = txtbarcode.getText();
        String qty = txtqty.getText();
        String cost_price = txtcost_price.getText();
        String rental_price = txtrental_price.getText();
        String reorder_level = txtreorder_level.getText();

        try {
            // TODO add your handling code here:
            pst = con.prepareStatement("update spareparts set Spare_Part=?, Description=?, Barcode=?, Qty=?, Cost_Price=?, Rental_Price=?, Reorder_Level=? where id=?");
            pst.setString(1, sparepart);
            pst.setString(2, description);
            pst.setString(3, barcode);
            pst.setString(4, qty);
            pst.setString(5, cost_price);
            pst.setString(6, rental_price);
            pst.setString(7, reorder_level);
            pst.setInt(8, id);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Spare Part Updated");

            txtsparepart.setText("");
            txtdescription.setText("");
            txtbarcode.setText("");
            txtqty.setText("");
            txtcost_price.setText("");
            txtrental_price.setText("");
            txtreorder_level.setText("");
            txtsparepart.requestFocus();
            load();
            jButton1.setEnabled(true);

        } catch (SQLException ex) {
            Logger.getLogger(Details.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {

            String sparepart = txtsparepart.getText();
            String description = txtdescription.getText();
            String barcode = txtbarcode.getText();
            String qty = txtqty.getText();
            String cost_price = txtcost_price.getText();
            String rental_price = txtrental_price.getText();
            String reorder_level = txtreorder_level.getText();

            // TODO add your handling code here:
            pst = con.prepareStatement("insert into spareparts (Spare_Part, Description, Barcode, Qty, Cost_Price, Rental_Price, Reorder_Level)values(?,?,?,?,?,?,?)");
            pst.setString(1, sparepart);
            pst.setString(2, description);
            pst.setString(3, barcode);
            pst.setString(4, qty);
            pst.setString(5, cost_price);
            pst.setString(6, rental_price);
            pst.setString(7, reorder_level);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Spare Part Added");
            txtsparepart.setText("");
            txtdescription.setText("");
            txtbarcode.setText("");
            txtqty.setText("");
            txtcost_price.setText("");
            txtrental_price.setText("");
            txtreorder_level.setText("");
            txtsparepart.requestFocus();
            load();

        } catch (SQLException ex) {
            Logger.getLogger(Details.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        df = (DefaultTableModel) jTable3.getModel();
        int selected = jTable3.getSelectedRow();

        int id = Integer.parseInt(df.getValueAt(selected, 0).toString());

        try {
            // TODO add your handling code here:
            pst = con.prepareStatement("delete from spareparts where id=?");
            pst.setInt(1, id);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Spare Part Deleted");
            txtsparepart.setText("");
            txtdescription.setText("");
            txtbarcode.setText("");
            txtqty.setText("");
            txtcost_price.setText("");
            txtrental_price.setText("");
            txtreorder_level.setText("");
            txtsparepart.requestFocus();
            load();
            jButton2.setEnabled(true);

        } catch (SQLException ex) {
            Logger.getLogger(Details.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        txtsparepart.setText("");
        txtdescription.setText("");
        txtbarcode.setText("");
        txtqty.setText("");
        txtcost_price.setText("");
        txtrental_price.setText("");
        txtreorder_level.setText("");
        txtsparepart.requestFocus();
        load();
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:

        df = (DefaultTableModel) jTable3.getModel();
        int selected = jTable3.getSelectedRow();

        int id = Integer.parseInt(df.getValueAt(selected, 0).toString());
        txtsparepart.setText(df.getValueAt(selected, 1).toString());
        txtdescription.setText(df.getValueAt(selected, 2).toString());
        txtbarcode.setText(df.getValueAt(selected, 3).toString());
        txtqty.setText(df.getValueAt(selected, 4).toString());
        txtcost_price.setText(df.getValueAt(selected, 5).toString());
        txtrental_price.setText(df.getValueAt(selected, 6).toString());
        txtreorder_level.setText(df.getValueAt(selected, 7).toString());
        jButton2.setEnabled(false);
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtsparepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsparepartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsparepartActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
           try {
            // TODO add your handling code here:
            jTable3.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Details.class.getName()).log(Level.SEVERE, null, ex);
        }
    


    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField txtbarcode;
    private javax.swing.JTextField txtcost_price;
    private javax.swing.JTextField txtdescription;
    private javax.swing.JTextField txtqty;
    private javax.swing.JTextField txtrental_price;
    private javax.swing.JTextField txtreorder_level;
    private javax.swing.JTextField txtsparepart;
    // End of variables declaration//GEN-END:variables
}
